FROM node:22.13.0

WORKDIR /app

ARG NODE_ENV
ARG VITE_SERVER_PORT

ENV NODE_ENV = ${NODE_ENV}
ENV VITE_SERVER_PORT=${VITE_SERVER_PORT}

COPY package*.json .

RUN npm install
COPY . . 
EXPOSE 2094

RUN npm run build

CMD ["npm", "run", "preview"]