FROM node:22.13.0-alpine AS builder

# Stage 1: Building React Application
WORKDIR /app

ARG NODE_ENV
ARG VITE_SERVER_PORT

ENV NODE_ENV = ${NODE_ENV}
ENV VITE_SERVER_PORT=${VITE_SERVER_PORT}

COPY package*.json .

# RUN npm install --legacy-peer-deps
RUN --mount=type=cache,target=/root/.npm npm install --legacy-peer-deps

COPY . . 

RUN npm run build

# Stage 2: Running React Application
FROM node:22.13.0 AS runner

# Set the working directory inside the container
WORKDIR /app
  
# Copy only the production build output from the builder stage
COPY --link --from=builder /app/dist ./dist
 
# Install only the `serve` package (no global install, pinned version)
RUN --mount=type=cache,target=/root/.npm npm install serve@^14.2.6 --omit=dev
 
# Run the container as a non-root user for security best practices
USER node
 
# Run `serve` directly to serve the built app
CMD ["sh", "-c", "./node_modules/.bin/serve -s dist -l tcp://0.0.0.0:${FRONTEND_PORT}"]

