version: "latest"
services:
  backend:
    image: ${DOCKERHUB_USERNAME}/whiteboard-backend:latest
    build: ./backend
    user: "1000:1000"
    cap_drop:
      - ALL
    environment:
      - NODE_ENV=${NODE_ENV}
      - BACKEND_PORT=${BACKEND_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - SALT_ROUNDS=${SALT_ROUNDS}
    deploy:
      replicas: ${BACKEND_REPLICAS:-1}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ${DOCKERHUB_USERNAME}/whiteboard-frontend:latest
    build:
      context: ./frontend
      args:
        - BACKEND_URL=${BACKEND_URL}
        - BACKEND_PORT=${NGINX_PORT}
    user: "1000:1000"
    cap_drop:
      - ALL
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - NODE_ENV=${NODE_ENV}
    deploy:
      replicas: ${FRONTEND_REPLICAS:-1}
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    volumes:
      - whiteboard-data:/var/lib/postgresql
      - ./data/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 10

  nginx:
    image: nginx:latest
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
      - NGINX_PORT=${NGINX_PORT}
    restart: always
    depends_on:
      - backend
      - frontend
      - db

volumes:
  whiteboard-data:
