name: Testing Docker Container
on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker Actions
      uses: docker/setup-buildx-action@v2

    - name: Build and Test
      run: |
        ./scripts/test.sh

    