name: Testing Docker Container
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker Actions
      uses: docker/setup-buildx-action@v2

    - name: Make script executable (if needed)
      run: chmod +x ./scripts/test.sh
      
    - name: Build and Test
      run: |
        ./scripts/test.sh
      env: 
        SERVER_PORT: ${{ vars.SERVER_PORT }}
        CORS_ORIGINS: ${{ vars.CORS_ORIGINS }}
        SALT_ROUNDS: ${{ vars.SALT_ROUNDS }}

        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        SECRET: ${{ secrets.SECRET }}
      

    